config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  resources :job_applications

  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.present?
      can :read, :all
      can :create, :job_application
      if user.admin?
        can :manage, :job, :job_application
        can :view, :all
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :job_applications
  searchkick

  #jobs = Job.search("")
  #jobs.each  do  |job|
    #puts job.title
   #end
  scope :filter_by_title, -> (title) {where title: title}

end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :job_applications

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
#  before_action :authenticate_user!, :expect =>[:index]
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: [:show, :update, :destroy]
  #before_action :authenticate_user!, except: [:show, :index]

  def index
    @jobApplcations = JobApplication.all
  end

  def show
  end

  def create
    @job_applcation = JobApplication.new(job_application_params)
    @job_applcation.user_id = current_user.id # current_user.id
    if @job_applcation.save
        render json: @job_applcation, status: :created
      else
        render json: @job_applcation.errors, status: :unprocessable_entity
    end
  end

  def update
    @job_application.update(job_applications_update_params)
    render json: @job_application
  end

  private

  def job_applications_update_params
    params.require(:job_application).permit(:status)
  end

  def job_application_params
    params.require(:job_application).permit(:job_id)
  end

  def set_job_application
    @job_application = JobApplication.find(params[:id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, except: [:show, :index]
  # GET /jobs
  # GET /jobs.json


  def index
    @jobs = Job.all
    render json: @jobs

    @jobss = Job.where(nil)
      filtering(params).each do |key, value|
        @jobss = @jobss.public_send("filter_by_#{key}", value) if value.present?
      end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
     if @job.save
        render json: @job, status: :created, location: @job
     else
        render json: @job.errors, status: :unprocessable_entity
     end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
      @job.update(job_params)
      render json: @job, status: :ok, location: @job
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
#      format.json { head :no_content }
  end

  private

  def filtering(params)
    params.slice(:title, :body)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

   def job_params
      params.require(:job).permit(:title, :body)
   end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.body %></td>
        <td><%= job.user.email %></td>
        <td><%= link_to 'Show', job %></td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% if current_user && current_user.admin %>
    <%= link_to 'New Job', new_job_path %>
  <% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @job.body %>
</p>

<p>
  <strong>User Email:</strong>
  <%= @job.user.email %>
</p>
<% if user_signed_in? %>
<!--   <p> <button onclick= " should call method to toggle the applied boolean so we know that this user applied for this position" > Apply for this position </button> </p> -->
<%end %>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--  <p class="notice"> <%#= notice %> </p>-->
<!--  <p class="alert"> <%#= alert %> </p>-->
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home page</h1>


<% if current_user %>
  <%= link_to :'Sign out', destroy_user_session_path, method: :delete %>

<% else %>
  <%= link_to :'Sign up', new_user_registration_path %>
  <%= link_to :'Sign in', new_user_session_path %>

<% end %>

<%= link_to :'Jobs', jobs_path %>